# Stage 1: Build
FROM node:22-alpine AS builder

LABEL org.opencontainers.image.authors="ittuann@outlook.com"

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN apk update \
    && apk add --no-cache git \
    && rm -rf /var/cache/apk/*

RUN npm install -g pnpm

COPY . /app

WORKDIR /app

RUN pnpm install --frozen-lockfile

RUN pnpm build

# Stage 2: Serve
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
